export interface INewItemTypes {
  bulkMixingFamilyId: string;
  categoryId: string;
  compartmentTypeProfileId: string;
  coreDiameter: string;
  defaultPck: boolean;
  description: string;
  diameterPerShipUnit: string;
  hazaradous: boolean;
  hazmatPckTypeId: string;
  innerPackPckUnit: string;
  innerPackSize: string;
  innerPckSizeUOMcode: string;
  itemId: string;
  loadConfigRuleRank: string;
  mixable: boolean;
  pckItemId: string;
  pckItemTypeId: string;
  pckUnit: string;
  pckWeight: string;
  pckWidth: string;
  priority: string;
  thuProfileId: string;
  unitHeight: string;
  unitLength: string;
  unitVolume: string;
  unitWidth: string;
  uuid: string;
}
